name: global_pandas
description: This tool allows users to search all wikis at once using CirrusSearch and other familiar stuff.
version: 0.2.1
homepage: https://global-pandas.toolforge.org

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  angular: ^7.0.2
  pool: ^1.5.0

dev_dependencies:
  build_runner: ^2.1.5
  build_web_compilers: ^3.2.1
  lints: ^1.0.1
